blood_donor_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # add the views from core app
    path('', views.Tabs.index, name='index'),
    path('blood_requests/', views.Tabs.blood_requests, name='blood_requests'),
    path('profile/', views.Tabs.profile, name='profile'),
    path('login/', views.Tabs.login, name='login'),
    path('login_success/', views.Authentication.login, name='login_success'),
    path('register/', views.Tabs.register, name='register'),
    path('signup_success/', views.Authentication.signup, name='signup_success'),
    path('logout/', views.Authentication.logout, name='logout'),
    path('blood_request_form/', views.Tabs.blood_request_form, name='blood_request_form'),
    path('blood_request_form_submit/', views.BloodRequests.form_function, name='blood_request_form_submit'),
    path('email_send/', views.BloodRequests.send_info_email, name='email_send'),
    # path('delete_blood_request/', views.BloodRequests.delete_request, name='delete_blood_request'),
    path('edit_extra/', views.Tabs.user_extra_contact, name='edit_extra'),
    path('edit_extra_submit/', views.User_Extra_Info.user_extra_info, name='edit_extra_submit'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

core/models.py
from pyexpat import model
from django.db import models
# import user 
from django.contrib.auth.models import User
# Create your models here.

class Blood_form(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    Age = models.IntegerField()
    blood_group = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    report = models.FileField(upload_to='media', blank = False, null = False)
    reason = models.CharField(max_length=50, blank=True, null=True, default=None)
    #  <!-- time in format of July 17, 2022 -->

    time = models.DateTimeField(auto_now_add=True, null=True)

    def save (self, *args, **kwargs):
        super().save(*args, **kwargs)
    def __str__(self):
        return self.name
    


class User_extra_contact(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.IntegerField()
    address = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    blood_group = models.CharField(max_length=50, default=None)
    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from .models import *


class Blood_Donor_Form(forms.ModelForm):
    class Meta:
        model = Blood_form
        fields = ['name', 'email', 'first_name', 'last_name', 'Age', 'blood_group', 'address', 'province', 'city', 'report', 'reason']

class User_extra_contact_form(forms.ModelForm):
    class Meta:
        model = User_extra_contact
        fields = ['phone_number', 'address', 'province', 'city', 'blood_group']

core/views.py
import email
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User 
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from numpy import logical_not
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from requests import request
from .forms import *
from django.core.mail import EmailMessage, send_mail
# Create your views here.
class Tabs:
    def index(self):
        blood_request_list = Blood_form.objects.all()
        context = {'blood_request_list': blood_request_list}
        return render(self, 'blood_requests.html', context)
    def blood_requests(self):
        return render(self, 'blood_requests.html')
    def profile(self):
        return render(self, 'profile.html')
    def login(self):
        return render(self, 'login.html')
    def register(self):
        return render(self, 'register.html')
    def blood_request_form(self):
        form  =  Blood_Donor_Form()
        context = {'form': form}
        return render(self, 'blood_request_form.html', context)
    def user_extra_contact(self):
        form  =  User_extra_contact_form()
        idd = self.POST.get('request_id')
        print(idd)
        data =  User_extra_contact.objects.get(id = idd)
        context = {'form': form, 'data': data}
        return render(self, 'edit_extra.html', context)

class Authentication:
    #---------------------------------------------------------------------------------
    # signup function
    #---------------------------------------------------------------------------------
    def signup(self):
        if self.method != 'POST':
            return redirect('register')
        username = self.POST['email']
        email = self.POST['username']
        password = self.POST['password']
        confirm_password = self.POST['confirm_password']
        first_name = self.POST['fname']
        last_name = self.POST['lname']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(self, 'Username already taken')
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(self, 'Email already taken')
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
                user.save()
                messages.info(self, 'User created')
                return redirect('login')
        else:
            messages.info(self, 'Password not matching')
            return redirect('register')
    # ------------------------------------------------------------------------------------
    # login function
    # ------------------------------------------------------------------------------------
    def login(self):
        if self.method != 'POST':
            return redirect('login')
        email = self.POST['email']
        password = self.POST['password']
        user = authenticate(self, username=email, password=password)
        if user is not None:
            login(self, user)
            return redirect('/')
        else:
            messages.info(self, 'Invalid credentials')
            return redirect('/login')
    # ------------------------------------------------------------------------------------
    # logout function
    # ------------------------------------------------------------------------------------
    def logout(self):
        logout(self)
        return redirect('/')
    
class BloodRequests:
    def form_function(request):
        if request.method == "POST":
            form = Blood_Donor_Form(request.POST, request.FILES)
            if form.is_valid():
                print("valid")
                form.save()
                # send email to the user that the request has been received and we will contact you if someone contacts you
                email_send = EmailMessage(
                    'Blood Request',
                    'Your blood request has been received. We have already sent the request to all the active donors. We will contact if someone accepts your request.',
                    settings.EMAIL_HOST_USER,
                    [request.POST['email']],
                    headers = {'Reply-To': settings.EMAIL_HOST_USER}
                )
                email_send.send()
                # now to all the donors
                email_list = User.objects.all()
            # get the email addresses from the database
                for em in email_list:
                    try:
                        print(em.username)
                        email_send_2 = EmailMessage(
                        'Blood Request',
                        'New Blood Request ! Please go to http://localhost:2500 to see the request.',
                        settings.EMAIL_HOST_USER,
                        [em.email],
                        reply_to=[settings.EMAIL_HOST_USER],
                        headers = {'Message-ID': 'foo'},
                        )
                        email_send_2.sub_type = 'html'
                        email_send_2.send()
                    except:
                        print("error")
                        
                return JsonResponse({'status': 'success'})
            else:
                print("Error")
        else:
            print("Error")
            return HttpResponseRedirect('/')

    def send_info_email(request):
        # get the logged in user info
        user = request.POST['use']
        user = int(user)
        user_info = User.objects.get(id=user)

        # print(use)
        email2 = Blood_form.objects.get( id = request.POST['requester_id'])
        # this email will be send to the requester email
        email_send = EmailMessage(
                'Blood Request Accepted',
                'Your blood request has been accepted. The contact info of the donor is : \n Name: ' + user_info.email + '\n Email: ' + user_info.username + ' ' ,
                settings.EMAIL_HOST_USER,
                [email2.email],
                reply_to=[settings.EMAIL_HOST_USER],
                headers = {'Message-ID': 'foo'},
        ).send()
        # also the requester info will go to the donor
        email_send = EmailMessage(
                'Blood Requester Info',
                'The info of the requester of the blood request you accepted is : \nName: ' + str(email2.first_name) + ' ' + str(email2.last_name)  + '\nEmail: ' +str( email2.email) +'\nHospital Address: '+ str(email2.address) + '\nAge: ' + str(email2.Age) + '\nBlood Group of the patient: ' + str(email2.blood_group) + '\nReason for the request: ' + str(email2.reason) + ' ' ,
                settings.EMAIL_HOST_USER,
                [user_info.username],
                reply_to=[settings.EMAIL_HOST_USER],
                headers = {'Message-ID': 'foo'},
        ).send()
        Blood_form.objects.get(id=email2.id).delete()
        return JsonResponse({'status': 'success'})

        # delete the request from the database after it has been accepted
    def delete_request(request):
        # get the accepted request post 
        request_id = request.POST['requester_id']
        request_id = int(request_id)
        # delete the request from the database
        Blood_form.objects.get(id=request_id).delete()
        print("deleted")
        return JsonResponse({'status': 'success'})

class User_Extra_Info:
    def user_extra_info(self):
        if self.method == 'POST':
            form = User_extra_contact_form(self.POST)
            if form.is_valid():
                form.instance.user = self.user
                form.save()
                return redirect('/')
            else:
                return redirect('/')


                

            

core/templates/blood_request_form.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Blood Request Form</title>
        <!-- links  -->
        {% include 'ELEMENTS/head_links.html' %}
        <!-- end links  -->
    </head>
<body>
    <div id="wrapper">
		<!-- NAVIGATION BAR  -->
			{% include 'ELEMENTS/navigation.html' %}
		<!-- NAVIGATION BAR END  -->
		<!-- TOP NAVBAR  -->
			{% include 'ELEMENTS/top_navbar.html' %}
            <div class="container">
                <div class="col">
                    <form method="post" enctype="multipart/form-data" action="{% url 'blood_request_form_submit' %}"  id="id_ajax_upload_form">
                        {% csrf_token %}
                        {{ form.media }}
                        <div class="card shadow mb-3">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 fw-bold">Blood Donor Form</p>
                            </div>
                            <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_name">
                                                    <strong>Your Name</strong>
                                                </label>
                                                    <input class="form-control" type="text" id="id_name" placeholder="Ram Bahadhur" name="name" required>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_email">
                                                    <strong>Email Address</strong>
                                                </label>
                                                <input class="form-control" type="email" id="id_email" placeholder="user@example.com" name="email">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_first_name">
                                                    <strong>First Name of the patient</strong>
                                                </label>
                                                    <input class="form-control" type="text" id="id_first_name" placeholder="John" name="first_name">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_last_name">
                                                    <strong>Last Name of the patient</strong>
                                                </label>
                                                    <input class="form-control" type="text" id="id_last_name" placeholder="Doe" name="last_name"></div>
                                            </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_Age">
                                                    <strong>Age</strong>
                                                </label>
                                                    <input class="form-control" type="text" id="id_Age" placeholder="25" name="Age">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <!-- blood group  -->
                                            <div class="mb-3">
                                                <label class="form-label" for="id_blood_group">
                                                    <strong>Blood Group</strong>
                                                </label>
                                                <select class="form-control" id="id_blood_group" name="blood_group">
                                                    <option value="A+">A+</option>
                                                    <option value="A-">A-</option>
                                                    <option value="B+">B+</option>
                                                    <option value="B-">B-</option>
                                                    <option value="AB+">AB+</option>
                                                    <option value="AB-">AB-</option>
                                                    <option value="O+">O+</option>
                                                    <option value="O-">O-</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                        <div class="card shadow">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 fw-bold">Contact Info</p>
                            </div>
                            <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_address">
                                                    <strong>Hospital Address</strong>
                                                </label>
                                                <input class="form-control" type="text" id="id_address" placeholder="Hospital Address" name="address">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_province">
                                                    <strong>Province</strong>
                                                </label>
                                                <!-- options -->
                                                    <select class="form-control" id="id_province" name="province">
                                                        <option value="">Select Province</option>
                                                        <option value="1">1</option>
                                                        <option value="2">2</option>
                                                        <option value="3">3</option>
                                                        <option value="Gandaki Province">Gandaki Pradesh</option>
                                                        <option value="5">5</option>
                                                        <option value="Karnali Province">Karnali Pradesh</option>
                                                        <option value="Sudurpashchim Province">Sudurpashchim Pradesh</option>
                                                    </select>
                                                <!-- end options -->
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_city">
                                                    <strong>City</strong>
                                                </label>
                                                <input class="form-control" type="text" id="id_city" placeholder="Kathmandu" name="city">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="country">
                                                    <strong>Country (Only available in Nepal for now)</strong>
                                                </label>
                                                    <input class="form-control" type="text" id="country" placeholder="Nepal" name="country" value="Nepal" readonly >
                                                </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="card shadow">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 fw-bold">Validity Info</p>
                            </div>
                            <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_report">
                                                    <strong>Medical Report ( For Conformation Only) </strong>
                                                </label>
                                                <!-- medical report upload only jpg, png-->
                                                <input type="file" name="report" id="id_report" class="form-control" onchange="validateFile()">
                                                <script>
                                                    function validateFile() {
                                                        var file = document.getElementById("file").value;
                                                        var allowedExtensions = /(\.jpg|\.jpeg|\.png)$/i;
                                                        if (!allowedExtensions.exec(file)) {
                                                            alert('Please upload file having extensions .jpeg/.jpg/.png only.');
                                                            document.getElementById("file").value = "";
                                                            return false;
                                                        }
                                                        else {
                                                            return true;
                                                        }
                                                    }

                                                </script>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <div class="mb-3">
                                                    <label class="form-label" for="id_reason">
                                                        <strong> Reason </strong>
                                                    </label>
                                                    <input class="form-control" id="id_reason" placeholder=" for eg: Blood Cancer " name="reason" >
                                                </div>
                                            </div>
                                    <div class="mb-3">
                                        {% csrf_token %}
                                        <button class="btn btn-primary btn-md" type="submit" style="background: #e02244;border:1px solid red;">
                                            Submit Request
                                            
                                        </button>
                                    </div>
                            </div>
                        </div>
                </form>
                </div>
            </div>
        </div>
        {% include 'ELEMENTS/footer.html' %}
     <!-- scripts -->
     {% include 'ELEMENTS/scripts.html' %}
     <!-- scripts end -->
     <script>
         $('#id_ajax_upload_form').submit(function (e) {
            e.preventDefault();
            var form = $(this);
            var formData = new FormData(this);

            $.ajax({
                url: form.attr('action'),
                type: form.attr('method'),
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                success: function (data) {
                    
                }
            });
            // go to the home page 
            window.location.href = "/";

        });
     </script>

</body>
</html>

core/templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login - Blood Donors</title>
    <!-- links  -->
	{% include 'ELEMENTS/head_links.html' %}
	<!-- end links  -->
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-flex">
                                <div class="flex-grow-1 bg-login-image">
                                        <img src="{% static 'assets/img/login.png' %}" class="img-fluid" alt="" style="object-fit: contain !important;height: 100% !important;">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4">Welcome Back!</h4>
                                    </div>
                                    <form class="user" method="POST" action="/login_success/">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <input class="form-control form-control-user" type="text" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address..." name="email">
                                        </div>
                                        <div class="mb-3">
                                            <input class="form-control form-control-user" type="password" id="password" placeholder="Password" name="password">
                                        </div>
                                        <div class="mb-3">
                                            <div class="custom-control custom-checkbox small">
                                                <div class="form-check">
                                                    <input class="form-check-input custom-control-input" type="checkbox" id="formCheck-1">
                                                        <label class="form-check-label custom-control-label" for="formCheck-1">Remember Me</label>
                                                    </div>
                                            </div>
                                        </div>
                                        <button class="btn btn-primary d-block btn-user w-100" type="submit">Login</button>
                                        <hr>
                                        <a class="btn btn-primary d-block btn-google btn-user w-100 mb-2" role="button">
                                            <i class="fab fa-google"></i>&nbsp; Login with Google
                                        </a>
                                        <a class="btn btn-primary d-block btn-facebook btn-user w-100" role="button">
                                            <i class="fab fa-facebook-f"></i>&nbsp; Login with Facebook
                                        </a>
                                        <hr>
                                    </form>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="/register">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- scripts -->
    {% include 'ELEMENTS/scripts.html' %}
    <!-- scripts end -->
</body>

</html>